### ISSUE TITLE
No "Additional options button" in the user interface

### ISSUE THREAD

**Issue by Diklaz** [Geoalert/mapflow-qgis#62]
**Describe the bug**
After installing Mapflow plugin 2.0.0 in qgis 3.30 , There is no "Additional options button" next to the "data sources" menu, so it is not possible to add images.
![image](https://github.com/Geoalert/mapflow-qgis/assets/131339826/e4fbfb00-36cd-4ca2-84bf-1f7e904f8ac2)

**Comment by AlexeyTrekin** [comment]
Thank you for the message!

The button was removed as it doubles basic QGIS functionality. If you add an image (via layer -> add raster layer, or just drag-and-drop into the work/layers area), it will immediately appear in the data source list.
