### ISSUE TITLE
Error "requires Internet connection"

### ISSUE THREAD

**Issue by laurascasse** [Geoalert/mapflow-qgis#9]
I think it's because i'm behind a proxy.
I try to exclude URL -https://mapflow.ai/- in QGIS Option but i stil have this problem.
Qgis 3.16 on win10

**Comment by GregNed** [comment]
Hi, thanks for bringing this up. We had another user report the same issue the other day. It seems that Requests can't handle proxies. We'll try to rewrite it using Qt's native networking API. In the meantime, try adding https://whitemaps-production.mapflow.ai/rest to your proxy settings, perhaps it'll work if you specify the subdomain. We'll keep you updated.

**Comment by GregNed** [comment]
Should be fixed in 1.4. Please, reopen if you still have trouble connecting from behind a proxy.

**Comment by GregNed** [comment]
Should be fixed in 1.4. Please, reopen if you still have trouble connecting from behind a proxy.
